# Generated by Django 4.2 on 2023-06-08 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docsupload', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
                ('Description', models.TextField(blank=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Description',
        ),
    ]
